import type { Metadata } from "next";
import PageHeader from "@/components/ui/PageHeader";
import Card from "@/components/ui/Card";

export const metadata: Metadata = {
  title: "Terms of Service — OwnYourMusic",
  description: "The terms that govern your use of OwnYourMusic.",
};

const SECTIONS = [
  {
    heading: "1. Who we are",
    body: (
      <p>
        OwnYourMusic (&ldquo;the Service,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) is operated by Own Your
        Music, based in Limoges, France.
      </p>
    ),
  },
  {
    heading: "2. What the Service does",
    body: (
      <>
        <p>
          OwnYourMusic helps musicians extract, validate, and organize their music catalog
          metadata (album and track information, ISRCs, UPCs, credits, and related data) to
          support switching between music distributors. The Service:
        </p>
        <ul>
          <li>
            Uses AI (via a third-party provider) to extract structured data from screenshots,
            PDFs, and other materials you upload — only during the import step.
          </li>
          <li>Runs deterministic, non-AI validation checks against your catalog data afterward.</li>
          <li>
            Generates reference materials (export packs, migration reports) to help you manually
            complete a distributor switch.
          </li>
          <li>
            <strong>
              Never logs into, automates, or submits anything on your behalf on any third-party
              distributor&rsquo;s platform.
            </strong>{" "}
            Every upload to a distributor is performed by you, manually, on that distributor&rsquo;s
            own site.
          </li>
        </ul>
      </>
    ),
  },
  {
    heading: "3. Your account and data",
    body: (
      <ul>
        <li>
          You&rsquo;re responsible for the accuracy of the catalog data you confirm within the
          Service. We provide extraction and validation tools, but you make the final call on
          what&rsquo;s saved to your catalog.
        </li>
        <li>
          You represent that you own or have the right to upload and process the music catalog
          data you submit to the Service.
        </li>
        <li>
          We do not store your master audio files. Audio file verification happens locally on
          your own device — audio bytes are never uploaded to or retained on our servers.
        </li>
      </ul>
    ),
  },
  {
    heading: "4. What we don't guarantee",
    body: (
      <>
        <p>
          The Service validates the <strong>completeness and internal consistency</strong> of your
          catalog data (the Migration Confidence Score, Preflight Checklist, and related
          features). We do not and cannot guarantee that:
        </p>
        <ul>
          <li>
            Your streaming statistics, playlist placements, or royalty history will be preserved
            when you move to a new distributor — this depends on factors outside our control,
            including how streaming platforms and distributors handle the transition.
          </li>
          <li>
            Any third-party distributor will accept, process, or correctly display the data or
            export packs generated by the Service.
          </li>
        </ul>
      </>
    ),
  },
  {
    heading: "5. Payment and refunds",
    body: (
      <>
        <p>OwnYourMusic is offered as a one-time purchase, not a subscription.</p>
        <p>
          <strong>Refund Policy</strong>
        </p>
        <p>
          We want you to be completely satisfied with Own Your Music. If the software doesn&rsquo;t
          work as advertised or you&rsquo;re unable to use it because of a technical issue that we
          can&rsquo;t resolve, you may request a refund within 14 days of purchase.
        </p>
        <p>
          <strong>Eligible for a refund</strong> — you may be eligible if:
        </p>
        <ul>
          <li>The software fails to function substantially as described.</li>
          <li>
            A technical issue prevents you from using the software and we cannot resolve it
            within a reasonable time.
          </li>
          <li>You accidentally purchased multiple copies of the same licence.</li>
        </ul>
        <p>
          <strong>Not eligible for a refund</strong> — refunds are generally not available if:
        </p>
        <ul>
          <li>You simply change your mind.</li>
          <li>The software has successfully completed the migration you purchased it for.</li>
          <li>You no longer need the software.</li>
          <li>
            The issue is caused by third-party distribution platforms changing their systems
            after purchase.
          </li>
          <li>Your computer or operating system does not meet the published minimum requirements.</li>
        </ul>
        <p>
          If you&rsquo;re experiencing a problem, please contact our support team first at{" "}
          <a href="mailto:wearegamechangers@outlook.com" className="text-ink underline hover:text-brass">
            wearegamechangers@outlook.com
          </a>
          . We&rsquo;ll always do our best to resolve the issue before considering a refund.
        </p>
      </>
    ),
  },
  {
    heading: "6. Acceptable use",
    body: (
      <p>
        You agree not to use the Service to process data you don&rsquo;t have the rights to,
        attempt to reverse-engineer or abuse the AI extraction pipeline, or use the Service in
        any way that violates applicable law.
      </p>
    ),
  },
  {
    heading: "7. Limitation of liability",
    body: (
      <p>
        To the maximum extent permitted by law, OwnYourMusic and its operator are not liable for
        indirect, incidental, or consequential damages arising from your use of the Service,
        including loss of streaming history, royalties, or catalog data, except where such
        liability cannot be excluded under applicable law.
      </p>
    ),
  },
  {
    heading: "8. Termination",
    body: (
      <p>
        You may stop using the Service and request deletion of your account and data at any time
        (see Privacy Policy). We may suspend access for violation of these terms.
      </p>
    ),
  },
  {
    heading: "9. Governing law",
    body: <p>These terms are governed by the laws of France.</p>,
  },
  {
    heading: "10. Changes to these terms",
    body: (
      <p>
        We may update these terms from time to time. Material changes will be noted with an
        updated &ldquo;Last updated&rdquo; date.
      </p>
    ),
  },
  {
    heading: "11. Contact",
    body: (
      <p>
        Questions about these terms:{" "}
        <a href="mailto:wearegamechangers@outlook.com" className="text-ink underline hover:text-brass">
          wearegamechangers@outlook.com
        </a>
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-paper px-6 py-10 pb-20">
      <div className="mx-auto max-w-3xl">
        <PageHeader eyebrow="Last updated: August 2026" title="Terms of Service" />

        <Card className="p-6 sm:p-10">
          <div className="space-y-8 text-base font-normal leading-relaxed text-ink/75 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_li]:leading-relaxed [&_p+p]:mt-3 [&_p+ul]:mt-3 [&_ul+p]:mt-3">
            {SECTIONS.map((section) => (
              <section key={section.heading}>
                <h2 className="font-display text-lg font-semibold text-ink mb-2">
                  {section.heading}
                </h2>
                {section.body}
              </section>
            ))}
          </div>
        </Card>
      </div>
    </main>
  );
}
